environment:
  matrix:
    - PYTHON: "C:\\Python27"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

test:
  - "guild/guild/scripts/guild.cmd check -nT"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
