environment:
  matrix:
    - PYTHON: "C:\\Python27"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "build.cmd %PYTHON%\\python.exe guild/guild/scripts/guild check -nT"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
