environment:
  matrix:
    - PYTHON: "C:\\Python27"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - "%PYTHON%\\python.exe guild\\scripts\\guild check -nT"

artifacts:
  - path: dist\*
