jobs:
  macos-python-2.7:
    macos:
      xcode: 9.2.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos-python-2.7-5-{{ checksum 'requirements.txt' }}-{{ checksum 'guild/view/package.json' }}
    - run:
        command: 'virtualenv venv

          source venv/bin/activate

          pip install -r requirements.txt

          pip install tensorflow

          cd guild/view && npm install'
        name: Install dependencies
    - save_cache:
        key: macos-python-2.7-5-{{ checksum 'requirements.txt' }}-{{ checksum 'guild/view/package.json' }}
        paths:
        - venv
    - run:
        command: 'source venv/bin/activate

          python setup.py bist_wheel'
        name: Build
    - run:
        command: 'source venv/bin/activate

          guild/scripts/guild check -T'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: 'source venv/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - macos-python-2.7:
        filters:
          branches:
            only: release
  version: 2
