jobs:
  uat-macos-python-3.6:
    macos:
      xcode: 9.2.0
    steps:
    - run:
        command: which pip
        name: Init env
    - run:
        command: sudo pip install guildai==0.3.1.dev4
        name: Install Guild
    - run:
        command: guild init -y
        name: Init Guild
    - run:
        command: 'true'
        name: User acceptance tests
    working_directory: '~'
version: 2
workflows:
  all:
    jobs:
    - uat-macos-python-3.6:
        filters:
          branches:
            only: uat
  version: 2
