jobs:
  macos_10.15-python_3.6:
    macos:
      xcode: 11.2.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos_10.15-python_3.6-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'brew install pyenv

          pyenv install 3.6.11

          sudo -H ~/.pyenv/versions/3.6.11/bin/python -m pip install --upgrade pip | cat

          sudo -H ~/.pyenv/versions/3.6.11/bin/python -m pip install --upgrade virtualenv | cat

          rm -rf build-env && ~/.pyenv/versions/3.6.11/bin/python -m virtualenv build-env

          . build-env/bin/activate

          build-env/bin/pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1800
    - save_cache:
        key: macos_10.15-python_3.6-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          ~/.pyenv/versions/3.6.11/bin/python setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1800
    - run:
        command: sudo -H ~/.pyenv/versions/3.6.11/bin/python -m pip install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1800
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          guild check -v --offline

          WORKSPACE=test-env UAT_SKIP=,remote-*,hiplot-* COLUMNS=999 EXAMPLES=examples guild check --uat'
        name: Test
        no_output_timeout: 1800
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          ~/.pyenv/versions/3.6.11/bin/python -m pip install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1800
    working_directory: ~/repo
  macos_10.15-python_3.7:
    macos:
      xcode: 11.2.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos_10.15-python_3.7-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'brew install pyenv

          pyenv install 3.7.9

          sudo -H ~/.pyenv/versions/3.7.9/bin/python -m pip install --upgrade pip | cat

          sudo -H ~/.pyenv/versions/3.7.9/bin/python -m pip install --upgrade virtualenv | cat

          rm -rf build-env && ~/.pyenv/versions/3.7.9/bin/python -m virtualenv build-env

          . build-env/bin/activate

          build-env/bin/pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1800
    - save_cache:
        key: macos_10.15-python_3.7-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          ~/.pyenv/versions/3.7.9/bin/python setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1800
    - run:
        command: sudo -H ~/.pyenv/versions/3.7.9/bin/python -m pip install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1800
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          guild check -v --offline

          WORKSPACE=test-env UAT_SKIP=,remote-*,hiplot-* COLUMNS=999 EXAMPLES=examples guild check --uat'
        name: Test
        no_output_timeout: 1800
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          ~/.pyenv/versions/3.7.9/bin/python -m pip install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1800
    working_directory: ~/repo
  macos_10.15-python_3.8:
    macos:
      xcode: 11.2.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos_10.15-python_3.8-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'brew install pyenv

          pyenv install 3.8.6

          sudo -H ~/.pyenv/versions/3.8.6/bin/python -m pip install --upgrade pip | cat

          sudo -H ~/.pyenv/versions/3.8.6/bin/python -m pip install --upgrade virtualenv | cat

          rm -rf build-env && ~/.pyenv/versions/3.8.6/bin/python -m virtualenv build-env

          . build-env/bin/activate

          build-env/bin/pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1800
    - save_cache:
        key: macos_10.15-python_3.8-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          ~/.pyenv/versions/3.8.6/bin/python setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1800
    - run:
        command: sudo -H ~/.pyenv/versions/3.8.6/bin/python -m pip install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1800
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          guild check -v --offline

          WORKSPACE=test-env UAT_SKIP=,remote-*,hiplot-* COLUMNS=999 EXAMPLES=examples guild check --uat'
        name: Test
        no_output_timeout: 1800
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          ~/.pyenv/versions/3.8.6/bin/python -m pip install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1800
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - macos_10.15-python_3.6:
        filters:
          branches:
            only:
            - release
            - pre-release
    - macos_10.15-python_3.7:
        filters:
          branches:
            only:
            - release
            - pre-release
    - macos_10.15-python_3.8:
        filters:
          branches:
            only:
            - release
            - pre-release
  version: 2
