jobs:
  linux-python-2.7:
    docker:
    - image: circleci/python:2.7-stretch-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python-2.7-5-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'virtualenv venv

          source venv/bin/activate

          pip install -r requirements.txt

          pip install tensorflow

          cd guild/view && npm install'
        name: Install dependencies
    - save_cache:
        key: linux-python-2.7-5-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - venv
    - run:
        command: 'source venv/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
    - run:
        command: 'source venv/bin/activate

          pip install dist/*.whl

          guild check -T

          mkdir -p /tmp/guild-uat/passed-tests

          touch /tmp/guild-uat/passed-tests/{fresh-install,install-required-pip-packages,check-without-tensorflow,install-tensorflow}

          guild check --uat'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: 'source venv/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - linux-python-2.7:
        filters:
          branches:
            only: release
  version: 2
