jobs:
  linux-python_2.7:
    docker:
    - image: circleci/python:2.7-stretch-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python_2.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          rm -rf build-env && python -m virtualenv build-env

          . build-env/bin/activate

          build-env/bin/pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: linux-python_2.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          guild check --offline

          WORKSPACE=test-env UAT_SKIP=,remote-*,hiplot-* COLUMNS=999 EXAMPLES=examples guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
  macos_10.14-python_2.7:
    macos:
      xcode: 11.1.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos_10.14-python_2.7-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip2 install --upgrade pip | cat

          sudo -H pip2 install --upgrade virtualenv==16.7.9 | cat

          rm -rf build-env && python2 -m virtualenv build-env

          . build-env/bin/activate

          build-env/bin/pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: macos_10.14-python_2.7-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python2 setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip2 install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          guild check --offline

          WORKSPACE=test-env UAT_SKIP=,remote-*,hiplot-* COLUMNS=999 EXAMPLES=examples guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip2 install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
  macos_10.15-python_2.7:
    macos:
      xcode: 11.2.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos_10.15-python_2.7-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip2 install --upgrade pip | cat

          sudo -H pip2 install --upgrade virtualenv==16.7.9 | cat

          rm -rf build-env && python2 -m virtualenv build-env

          . build-env/bin/activate

          build-env/bin/pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: macos_10.15-python_2.7-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python2 setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip2 install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          guild check --offline

          WORKSPACE=test-env UAT_SKIP=,remote-*,hiplot-* COLUMNS=999 EXAMPLES=examples guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip2 install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - linux-python_2.7:
        filters:
          branches:
            only:
            - release
            - pre-release
    - macos_10.14-python_2.7:
        filters:
          branches:
            only:
            - release
            - pre-release
    - macos_10.15-python_2.7:
        filters:
          branches:
            only:
            - release
            - pre-release
  version: 2
