jobs:
  macos-python-3.6:
    macos:
      xcode: 9.2.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos-python-3.6-8-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'brew upgrade python > /dev/null

          sudo pip install virtualenv

          virtualenv build-env

          . build-env/bin/activate

          pip install -qr requirements.txt

          pip install -q tensorflow

          cd guild/view && npm install'
        name: Install dependencies
    - save_cache:
        key: macos-python-3.6-8-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel'
        name: Build
    - run:
        command: 'virtualenv test-env

          . test-env/bin/activate

          pip install dist/*.whl

          WORKSPACE=test-env guild check --uat'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - macos-python-3.6:
        filters:
          branches:
            only: release
  version: 2
