jobs:
  macos:
    macos:
      xcode: 9.2.0
    steps:
    - restore_cache:
        keys:
        - macos-4-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'test -e venv || virtualenv venv

          source venv/bin/activate

          pip install -r requirements.txt

          pip install tensorflow

          cd guild/view && npm install'
        name: Install dependencies
    - save_cache:
        key: macos-4-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - venv
    - run:
        command: 'source venv/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
    - run:
        command: 'source venv/bin/activate

          guild/scripts/guild check -T'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: 'source venv/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - macos:
        filters:
          branches:
            only: release
  version: 2
