jobs:
  linux-python_3.8:
    docker:
    - image: circleci/python:3.8.1-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python_3.8-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          rm -rf build-env && python -m virtualenv build-env

          . build-env/bin/activate

          build-env/bin/pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1800
    - save_cache:
        key: linux-python_3.8-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
        no_output_timeout: 1800
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1800
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          guild check --offline

          WORKSPACE=test-env UAT_SKIP=*keras*,*logreg*,*mnist*,*tensorflow*,simple-example,remote-*,hiplot-* COLUMNS=999 EXAMPLES=examples guild check --uat'
        name: Test
        no_output_timeout: 1800
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1800
    working_directory: ~/repo
  macos_10.14-python_3.8:
    macos:
      xcode: 11.1.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos_10.14-python_3.8-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'brew unlink python

          brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/a4ae4d46b34a94414188518335e5dd96e4ae4ea9/Formula/python@3.8.rb > /dev/null

          brew link python@3.8 --overwrite --force

          sudo -H pip3.8 install --upgrade pip | cat

          sudo -H pip3.8 install --upgrade virtualenv | cat

          rm -rf build-env && python3.8 -m virtualenv build-env

          . build-env/bin/activate

          build-env/bin/pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1800
    - save_cache:
        key: macos_10.14-python_3.8-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python3.8 setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1800
    - run:
        command: sudo -H pip3.8 install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1800
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          guild check --offline

          WORKSPACE=test-env UAT_SKIP=*keras*,*logreg*,*mnist*,*tensorflow*,simple-example,remote-*,hiplot-* COLUMNS=999 EXAMPLES=examples guild check --uat'
        name: Test
        no_output_timeout: 1800
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip3.8 install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1800
    working_directory: ~/repo
  macos_10.15-python_3.8:
    macos:
      xcode: 11.2.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos_10.15-python_3.8-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'brew unlink python

          brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/a4ae4d46b34a94414188518335e5dd96e4ae4ea9/Formula/python@3.8.rb > /dev/null

          brew link python@3.8 --overwrite --force

          sudo -H pip3.8 install --upgrade pip | cat

          sudo -H pip3.8 install --upgrade virtualenv | cat

          rm -rf build-env && python3.8 -m virtualenv build-env

          . build-env/bin/activate

          build-env/bin/pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1800
    - save_cache:
        key: macos_10.15-python_3.8-19-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python3.8 setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1800
    - run:
        command: sudo -H pip3.8 install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1800
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          guild check --offline

          WORKSPACE=test-env UAT_SKIP=*keras*,*logreg*,*mnist*,*tensorflow*,simple-example,remote-*,hiplot-* COLUMNS=999 EXAMPLES=examples guild check --uat'
        name: Test
        no_output_timeout: 1800
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip3.8 install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1800
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - linux-python_3.8:
        filters:
          branches:
            only:
            - release
            - pre-release
    - macos_10.14-python_3.8:
        filters:
          branches:
            only:
            - release
            - pre-release
    - macos_10.15-python_3.8:
        filters:
          branches:
            only:
            - release
            - pre-release
  version: 2
