jobs:
  linux-python-2.7:
    docker:
    - image: circleci/python:2.7-stretch-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python-2.7-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          test -e build-env/bin/activate || virtualenv build-env

          . build-env/bin/activate

          pip install --upgrade -r requirements.txt | cat

          pip install --upgrade grpcio==1.9.1 tensorflow | cat

          cd guild/view && npm install'
        name: Install build dependencies
    - save_cache:
        key: linux-python-2.7-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
    - run:
        command: 'guild init -y --no-progress --name guild-test --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* guild check --uat'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
  linux-python-3.5:
    docker:
    - image: circleci/python:3.5-jessie-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python-3.5-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          test -e build-env/bin/activate || virtualenv build-env

          . build-env/bin/activate

          pip install --upgrade -r requirements.txt | cat

          pip install --upgrade grpcio==1.9.1 tensorflow | cat

          cd guild/view && npm install'
        name: Install build dependencies
    - save_cache:
        key: linux-python-3.5-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
    - run:
        command: 'guild init -y --no-progress --name guild-test --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* guild check --uat'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
  linux-python-3.6:
    docker:
    - image: circleci/python:3.6-stretch-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python-3.6-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          test -e build-env/bin/activate || virtualenv build-env

          . build-env/bin/activate

          pip install --upgrade -r requirements.txt | cat

          pip install --upgrade grpcio==1.9.1 tensorflow | cat

          cd guild/view && npm install'
        name: Install build dependencies
    - save_cache:
        key: linux-python-3.6-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
    - run:
        command: 'guild init -y --no-progress --name guild-test --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* guild check --uat'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
  macos-python-2.7:
    macos:
      xcode: 9.2.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos-python-2.7-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          test -e build-env/bin/activate || virtualenv build-env

          . build-env/bin/activate

          pip install --upgrade -r requirements.txt | cat

          pip install --upgrade grpcio==1.9.1 tensorflow | cat

          cd guild/view && npm install'
        name: Install build dependencies
    - save_cache:
        key: macos-python-2.7-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel'
        name: Build
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
    - run:
        command: 'guild init -y --no-progress --name guild-test --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* guild check --uat'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
  macos-python-3.6:
    macos:
      xcode: 9.2.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos-python-3.6-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'brew unlink python

          brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb > /dev/null

          sudo -H pip3 install --upgrade pip | cat

          sudo -H pip3 install --upgrade virtualenv | cat

          test -e build-env/bin/activate || virtualenv build-env

          . build-env/bin/activate

          pip3 install --upgrade -r requirements.txt | cat

          pip3 install --upgrade grpcio==1.9.1 tensorflow | cat

          cd guild/view && npm install'
        name: Install build dependencies
    - save_cache:
        key: macos-python-3.6-15-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel'
        name: Build
    - run:
        command: sudo -H pip3 install --upgrade dist/*.whl | cat
        name: Install dist
    - run:
        command: 'guild init -y --no-progress --name guild-test --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* guild check --uat'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - linux-python-2.7:
        filters:
          branches:
            only: release
      linux-python-2.7-pre:
        filters:
          branches:
            only: pre-release
    - linux-python-3.5:
        filters:
          branches:
            only: release
      linux-python-3.5-pre:
        filters:
          branches:
            only: pre-release
    - linux-python-3.6:
        filters:
          branches:
            only: release
      linux-python-3.6-pre:
        filters:
          branches:
            only: pre-release
    - macos-python-2.7:
        filters:
          branches:
            only: release
      macos-python-2.7-pre:
        filters:
          branches:
            only: pre-release
    - macos-python-3.6:
        filters:
          branches:
            only: release
      macos-python-3.6-pre:
        filters:
          branches:
            only: pre-release
  version: 2
