jobs:
  uat-macos-python-3.6:
    macos:
      xcode: 9.2.0
    steps: []
    working_directory: '~'
version: 2
workflows:
  all:
    jobs:
    - uat-macos-python-3.6:
        filters:
          branches:
            only: uat
  version: 2
