jobs:
  macos-python-2.7:
    macos:
      xcode: 9.2.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos-python-2.7-6-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo pip install virtualenv

          virtualenv venv

          source venv/bin/activate

          pip install -r requirements.txt

          pip install tensorflow

          cd guild/view && npm install'
        name: Install dependencies
    - save_cache:
        key: macos-python-2.7-6-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - venv
    - run:
        command: 'source venv/bin/activate

          python setup.py bdist_wheel'
        name: Build
    - run:
        command: 'source venv/bin/activate

          pip install dist/*.whl

          guild check -T

          mkdir -p ./guild-uat/passed-tests

          touch ./guild-uat/passed-tests/{fresh-install,install-required-pip-packages,check-without-tensorflow}

          git clone https://github.com/guildai/examples.git ../guild-examples

          git clone https://github.com/guildai/packages.git ../guild-packages

          WORKSPACE=./guild-uat guild check --uat'
        name: Test
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: 'source venv/bin/activate

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - macos-python-2.7:
        filters:
          branches:
            only: release
  version: 2
