version: 2

jobs:

  linux-python-2.7:
    docker:
      - image: circleci/python:2.7-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - linux-python-2.7-1-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}

      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install tensorflow

      - save_cache:
          paths:
            - venv
          key: linux-python-2.7-1-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}

      - run:
          name: Build
          command: |
            source venv/bin/activate
            python setup.py bdist_wheel -p manylinux1_x86_64

      - run:
          name: Test
          command: |
            source venv/bin/activate
            guild/scripts/guild check -nT

      - store_artifacts:
          path: dist
          destination: dist

      - run:
          name: Upload to PyPI
          command: |
            twine upload dest/*.whl

  linux-python-3.5:
    docker:
      - image: circleci/python:3.5-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - linux-python-3.5-1-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install tensorflow

      - save_cache:
          paths:
            - venv
          key: linux-python-3.5-1-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}

      - run:
          name: Build
          command: |
            source venv/bin/activate
            python3 setup.py bdist_wheel -p manylinux1_x86_64

      - store_artifacts:
          path: dist
          destination: dist

  linux-python-3.6:
    docker:
      - image: circleci/python:3.6-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - linux-python-3.6-1-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install tensorflow

      - save_cache:
          paths:
            - venv
          key: linux-python-3.6-1-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}

      - run:
          name: Build
          command: |
            source venv/bin/activate
            python3 setup.py bdist_wheel -p manylinux1_x86_64

      - store_artifacts:
          path: dist
          destination: dist

workflows:
  version: 2
  all:
    jobs:
      - linux-python-2.7:
          filters:
            branches:
              only: release
      #- linux-python-3.5
      #- linux-python-3.6
