jobs:
  linux-python-2.7:
    docker:
    - image: circleci/python:2.7-stretch-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python-2.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          rm -rf build-env && python -m virtualenv build-env

          . build-env/bin/activate

          pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: linux-python-2.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* COLUMNS=999 guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
  linux-python-3.5:
    docker:
    - image: circleci/python:3.5-stretch-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python-3.5-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          rm -rf build-env && python -m virtualenv build-env

          . build-env/bin/activate

          pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: linux-python-3.5-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* COLUMNS=999 guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
  linux-python-3.6:
    docker:
    - image: circleci/python:3.6-stretch-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python-3.6-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          rm -rf build-env && python -m virtualenv build-env

          . build-env/bin/activate

          pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: linux-python-3.6-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* COLUMNS=999 guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
  linux-python-3.7:
    docker:
    - image: circleci/python:3.7-stretch-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - linux-python-3.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip install --upgrade pip | cat

          sudo -H pip install --upgrade virtualenv | cat

          rm -rf build-env && python -m virtualenv build-env

          . build-env/bin/activate

          pip install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: linux-python-3.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python setup.py bdist_wheel -p manylinux1_x86_64'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* COLUMNS=999 guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
  macos-python-2.7:
    macos:
      xcode: 11.2.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos-python-2.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'sudo -H pip2 install --upgrade pip | cat

          sudo -H pip2 install --upgrade virtualenv | cat

          rm -rf build-env && python2 -m virtualenv build-env

          . build-env/bin/activate

          pip2 install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: macos-python-2.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python2 setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip2 install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* COLUMNS=999 guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip2 install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
  macos-python-3.6:
    macos:
      xcode: 11.2.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos-python-3.6-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'brew unlink python

          brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb > /dev/null

          brew link python

          sudo -H pip3 install --upgrade pip | cat

          sudo -H pip3 install --upgrade virtualenv | cat

          rm -rf build-env && python3 -m virtualenv build-env

          . build-env/bin/activate

          pip3 install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: macos-python-3.6-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python3 setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip3 install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* COLUMNS=999 guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip3 install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
  macos-python-3.7:
    macos:
      xcode: 11.2.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - macos-python-3.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
    - run:
        command: 'brew unlink python

          brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/2efdfe5519df7654ece8d70786baa298e568eafd/Formula/python.rb > /dev/null

          brew link python

          sudo -H pip3 install --upgrade pip | cat

          sudo -H pip3 install --upgrade virtualenv | cat

          rm -rf build-env && python3 -m virtualenv build-env

          . build-env/bin/activate

          pip3 install --upgrade -r requirements.txt | cat

          cd guild/view && npm install'
        name: Install build dependencies
        no_output_timeout: 1200
    - save_cache:
        key: macos-python-3.7-17-{{ checksum "requirements.txt" }}-{{ checksum "guild/view/package.json" }}
        paths:
        - build-env
    - run:
        command: '. build-env/bin/activate

          python3 setup.py bdist_wheel'
        name: Build
        no_output_timeout: 1200
    - run:
        command: sudo -H pip3 install --upgrade dist/*.whl | cat
        name: Install dist
        no_output_timeout: 1200
    - run:
        command: 'guild init -y --no-progress --name guild-test --no-reqs --guild dist/*.whl test-env

          TERM=xterm-256color source guild-env test-env

          WORKSPACE=test-env UAT_SKIP=remote-* COLUMNS=999 guild check --uat'
        name: Test
        no_output_timeout: 1200
    - store_artifacts:
        destination: dist
        path: dist
    - run:
        command: '. build-env/bin/activate

          pip3 install --upgrade twine | cat

          twine upload --skip-existing dist/*.whl'
        name: Upload to PyPI
        no_output_timeout: 1200
    working_directory: ~/repo
version: 2
workflows:
  all:
    jobs:
    - linux-python-2.7:
        filters:
          branches:
            only:
            - release
            - pre-release
    - linux-python-3.5:
        filters:
          branches:
            only:
            - release
            - pre-release
    - linux-python-3.6:
        filters:
          branches:
            only:
            - release
            - pre-release
    - linux-python-3.7:
        filters:
          branches:
            only:
            - release
            - pre-release
    - macos-python-2.7:
        filters:
          branches:
            only:
            - release
            - pre-release
    - macos-python-3.6:
        filters:
          branches:
            only:
            - release
            - pre-release
    - macos-python-3.7:
        filters:
          branches:
            only:
            - release
            - pre-release
  version: 2
